name: ubuntu-tests

on:
  push:
    branches: ["workflow-testing"]
  pull_request:
    branches: ["workflow-testing"]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        cxx: [g++-12, g++-13, g++-14, clang++-18]

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
          lcov \
          libxrandr-dev \
          libxcursor-dev \
          libudev-dev \
          libopenal-dev \
          libflac-dev \
          libvorbis-dev \
          libgl1-mesa-dev \
          libegl1-mesa-dev \
          freeglut3-dev \
          cmake \
          g++ \
          python3-pip

      - name: Configure CMake to use Clang
        run: |
          export CC=clang
          export CXX=clang++
          cmake -B ${{github.workspace}}/build \
          -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
          -DCMAKE_CXX_STANDARD=20 \
          -DENABLE_COVERAGE=true \
          -DCMAKE_CXX_COMPILER=clang++ \
          -DCMAKE_C_COMPILER=clang

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest --output-on-failure
